version: '3.9'
services:
  postgresql:
    image: bitnami/postgresql:11
    container_name: bitnami_postgresql
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_redmine
      - POSTGRESQL_DATABASE=bitnami_redmine
  redmine:
    image: bitnami/redmine:5
    container_name: bitnami_redmine
    ports:
      - '9080:3000'
    volumes:
      - './redmine/config.ru:/opt/bitnami/redmine/config.ru'
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - postgresql
    environment:
      - REDMINE_LANGUAGE=ja
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_TYPE=postgresql
      - REDMINE_DATABASE_HOST=postgresql
      - REDMINE_DATABASE_PORT_NUMBER=5432
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
      - RAILS_RELATIVE_URL_ROOT=/redmine
volumes:
  postgresql_data:
    driver: local
  redmine_data:
    driver: local
